name: Daily Stock Screener

on:
  schedule:
    - cron: '30 3 * * *' # Runs at 09:00 AM IST approx
  workflow_dispatch:      # Allows manual testing button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Updated to fix the warning

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Screener Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCREENER_COOKIE: ${{ secrets.SCREENER_COOKIE }}
          SCREENER_URL: ${{ secrets.SCREENER_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # <--- THIS WAS MISSING
        run: python main.py
